ground_truth_dir = "./Hippocampus_Language_Framework/saved/ground_truths"
pca_and_mds_matrices_dir = "./Hippocampus_Language_Framework/saved/pca_and_mds_matrices"
plots_dir = "./Hippocampus_Language_Framework/saved/plots"
prediction_matrices_dir = "./Hippocampus_Language_Framework/saved/prediction_matrices"
saved_models_dir = "./Hippocampus_Language_Framework/saved/Saved_Models"
tensorboard_dir = "./Hippocampus_Language_Framework/Tensorboard/logs"
